pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from git branch main"
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/DevPhil01/alx-backend-python.git',
                        credentialsId: 'github-creds'
                    ]]
                ])
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    echo "Installing dependencies..."
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    echo "Running tests with pytest..."
                    pytest --junitxml=messaging_app/reports/results.xml || true
                '''
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'messaging_app/reports/results.xml'
                    archiveArtifacts artifacts: 'messaging_app/reports/**', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completed successfully!"
        }
    }
}
