pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/DevPhil01/alx-backend-python.git',
                        credentialsId: 'github-creds'
                    ]]
                ])
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    echo "Setting up Python virtual environment..."
                    python3 -m venv venv
                    . venv/bin/activate
                    python -m pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    echo "Running tests with pytest..."
                    . venv/bin/activate
                    pytest --junitxml=messaging_app/reports/results.xml || true
                '''
            }
            post {
                alw
